name: myapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  intl: ^0.18.1
  table_calendar: ^3.0.9
  file_picker: ^6.1.1
  mask_text_input_formatter: ^2.6.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Relogio_imagem.png
    - assets/Barba_imagem.png
    - assets/Degrade_imagem.png
    - assets/Nevou_imagem.png
    - assets/Sobrancelha_imagem.png
    - assets/Social_imagem.png
    - assets/Barbersync_logo.png
    - assets/Barbersync_logo_novo.png
    - assets/Joao_imagem.png
    - assets/Carlos_imagem.png
    - assets/Lucas_imagem.png
    
